### PR TITLE
Fix to be compatible with "jquery.inputmask: 3.x"

### PR DESCRIPTION
**Pull request by klimov-paul**
This PR updates the plugin to be compatible with "jquery.inputmask"  version "3.x".
Have been successfully tested against "3.2.2" in particular.

### CODE REVIEW

**Comment by klimov-paul** [comment]
Note: I am not sure, which changes should be made at "inputmask-multi.jquery.json".
I assume it should be:

```json
"jquery.inputmask": ">3.0",
```

**Comment by andr-04** [comment]
Thanks @klimov-paul! I'll fix requirements soon.

**Comment by andr-04** [comment]
Fixed another bugs and updated all manifests. And the demo -- now all works perfect with last version of inputmask (some bugs in inputmask also was fixed in master).

**Comment by klimov-paul** [comment]
Thanks for the release.

**Pull request merged**
